# Generated by Django 4.2.2 on 2023-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ thanh toán'), ('paid', 'Đã thanh toán')], default='pending', max_length=20),
        ),
    ]
