# Generated by Django 4.2.2 on 2023-07-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(default=176, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
