# Generated by Django 4.2.2 on 2023-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_room_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
