# Generated by Django 4.2.2 on 2023-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_room_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Khả dụng'), ('booked', 'Đã được đặt'), ('in_use', 'Đang sử dụng')], default='available', max_length=20),
        ),
    ]
