# Generated by Django 4.2.2 on 2023-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_out_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
